// Code generated by protoc-gen-go.
// source: kamaji.proto
// DO NOT EDIT!

/*
Package proto_msg is a generated protocol buffer package.

It is generated from these files:
	kamaji.proto

It has these top-level messages:
	KamajiMessage
*/
package proto_msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type KamajiMessage_ACTION int32

const (
	KamajiMessage_STATUS_UPDATE KamajiMessage_ACTION = 1
	KamajiMessage_ASSIGN        KamajiMessage_ACTION = 2
	KamajiMessage_QUERY         KamajiMessage_ACTION = 3
)

var KamajiMessage_ACTION_name = map[int32]string{
	1: "STATUS_UPDATE",
	2: "ASSIGN",
	3: "QUERY",
}
var KamajiMessage_ACTION_value = map[string]int32{
	"STATUS_UPDATE": 1,
	"ASSIGN":        2,
	"QUERY":         3,
}

func (x KamajiMessage_ACTION) Enum() *KamajiMessage_ACTION {
	p := new(KamajiMessage_ACTION)
	*p = x
	return p
}
func (x KamajiMessage_ACTION) String() string {
	return proto.EnumName(KamajiMessage_ACTION_name, int32(x))
}
func (x *KamajiMessage_ACTION) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(KamajiMessage_ACTION_value, data, "KamajiMessage_ACTION")
	if err != nil {
		return err
	}
	*x = KamajiMessage_ACTION(value)
	return nil
}

type KamajiMessage_ENTITY int32

const (
	KamajiMessage_NODE    KamajiMessage_ENTITY = 11
	KamajiMessage_JOB     KamajiMessage_ENTITY = 12
	KamajiMessage_TASK    KamajiMessage_ENTITY = 13
	KamajiMessage_COMMAND KamajiMessage_ENTITY = 14
)

var KamajiMessage_ENTITY_name = map[int32]string{
	11: "NODE",
	12: "JOB",
	13: "TASK",
	14: "COMMAND",
}
var KamajiMessage_ENTITY_value = map[string]int32{
	"NODE":    11,
	"JOB":     12,
	"TASK":    13,
	"COMMAND": 14,
}

func (x KamajiMessage_ENTITY) Enum() *KamajiMessage_ENTITY {
	p := new(KamajiMessage_ENTITY)
	*p = x
	return p
}
func (x KamajiMessage_ENTITY) String() string {
	return proto.EnumName(KamajiMessage_ENTITY_name, int32(x))
}
func (x *KamajiMessage_ENTITY) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(KamajiMessage_ENTITY_value, data, "KamajiMessage_ENTITY")
	if err != nil {
		return err
	}
	*x = KamajiMessage_ENTITY(value)
	return nil
}

type KamajiMessage struct {
	Action           *KamajiMessage_ACTION        `protobuf:"varint,1,req,name=action,enum=proto_msg.KamajiMessage_ACTION,def=1" json:"action,omitempty"`
	Entity           *KamajiMessage_ENTITY        `protobuf:"varint,2,req,name=entity,enum=proto_msg.KamajiMessage_ENTITY,def=11" json:"entity,omitempty"`
	Id               *string                      `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Messageitems     []*KamajiMessage_NodeItem    `protobuf:"bytes,4,rep,name=messageitems" json:"messageitems,omitempty"`
	Jobitems         []*KamajiMessage_JobItem     `protobuf:"bytes,5,rep,name=jobitems" json:"jobitems,omitempty"`
	Taskitems        []*KamajiMessage_TaskItem    `protobuf:"bytes,6,rep,name=taskitems" json:"taskitems,omitempty"`
	Commanditems     []*KamajiMessage_CommandItem `protobuf:"bytes,7,rep,name=commanditems" json:"commanditems,omitempty"`
	Statusupdate     *KamajiMessage_StatusUpdate  `protobuf:"group,8,opt,name=StatusUpdate" json:"statusupdate,omitempty"`
	Nodestats        *KamajiMessage_NodeStats     `protobuf:"group,11,opt,name=NodeStats" json:"nodestats,omitempty"`
	Commandlog       *KamajiMessage_CommandLog    `protobuf:"group,13,opt,name=CommandLog" json:"commandlog,omitempty"`
	Command          *KamajiMessage_Command       `protobuf:"group,15,opt,name=Command" json:"command,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *KamajiMessage) Reset()         { *m = KamajiMessage{} }
func (m *KamajiMessage) String() string { return proto.CompactTextString(m) }
func (*KamajiMessage) ProtoMessage()    {}

const Default_KamajiMessage_Action KamajiMessage_ACTION = KamajiMessage_STATUS_UPDATE
const Default_KamajiMessage_Entity KamajiMessage_ENTITY = KamajiMessage_NODE

func (m *KamajiMessage) GetAction() KamajiMessage_ACTION {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return Default_KamajiMessage_Action
}

func (m *KamajiMessage) GetEntity() KamajiMessage_ENTITY {
	if m != nil && m.Entity != nil {
		return *m.Entity
	}
	return Default_KamajiMessage_Entity
}

func (m *KamajiMessage) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *KamajiMessage) GetMessageitems() []*KamajiMessage_NodeItem {
	if m != nil {
		return m.Messageitems
	}
	return nil
}

func (m *KamajiMessage) GetJobitems() []*KamajiMessage_JobItem {
	if m != nil {
		return m.Jobitems
	}
	return nil
}

func (m *KamajiMessage) GetTaskitems() []*KamajiMessage_TaskItem {
	if m != nil {
		return m.Taskitems
	}
	return nil
}

func (m *KamajiMessage) GetCommanditems() []*KamajiMessage_CommandItem {
	if m != nil {
		return m.Commanditems
	}
	return nil
}

func (m *KamajiMessage) GetStatusupdate() *KamajiMessage_StatusUpdate {
	if m != nil {
		return m.Statusupdate
	}
	return nil
}

func (m *KamajiMessage) GetNodestats() *KamajiMessage_NodeStats {
	if m != nil {
		return m.Nodestats
	}
	return nil
}

func (m *KamajiMessage) GetCommandlog() *KamajiMessage_CommandLog {
	if m != nil {
		return m.Commandlog
	}
	return nil
}

func (m *KamajiMessage) GetCommand() *KamajiMessage_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

type KamajiMessage_StatusUpdate struct {
	Destination      *int32  `protobuf:"varint,9,req,name=destination" json:"destination,omitempty"`
	Name             *string `protobuf:"bytes,10,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *KamajiMessage_StatusUpdate) Reset()         { *m = KamajiMessage_StatusUpdate{} }
func (m *KamajiMessage_StatusUpdate) String() string { return proto.CompactTextString(m) }
func (*KamajiMessage_StatusUpdate) ProtoMessage()    {}

func (m *KamajiMessage_StatusUpdate) GetDestination() int32 {
	if m != nil && m.Destination != nil {
		return *m.Destination
	}
	return 0
}

func (m *KamajiMessage_StatusUpdate) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type KamajiMessage_NodeStats struct {
	Hostname         *string `protobuf:"bytes,12,req,name=hostname" json:"hostname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *KamajiMessage_NodeStats) Reset()         { *m = KamajiMessage_NodeStats{} }
func (m *KamajiMessage_NodeStats) String() string { return proto.CompactTextString(m) }
func (*KamajiMessage_NodeStats) ProtoMessage()    {}

func (m *KamajiMessage_NodeStats) GetHostname() string {
	if m != nil && m.Hostname != nil {
		return *m.Hostname
	}
	return ""
}

type KamajiMessage_CommandLog struct {
	Logline          *string `protobuf:"bytes,14,req,name=logline" json:"logline,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *KamajiMessage_CommandLog) Reset()         { *m = KamajiMessage_CommandLog{} }
func (m *KamajiMessage_CommandLog) String() string { return proto.CompactTextString(m) }
func (*KamajiMessage_CommandLog) ProtoMessage()    {}

func (m *KamajiMessage_CommandLog) GetLogline() string {
	if m != nil && m.Logline != nil {
		return *m.Logline
	}
	return ""
}

type KamajiMessage_Command struct {
	ID               *string `protobuf:"bytes,16,req,name=ID" json:"ID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *KamajiMessage_Command) Reset()         { *m = KamajiMessage_Command{} }
func (m *KamajiMessage_Command) String() string { return proto.CompactTextString(m) }
func (*KamajiMessage_Command) ProtoMessage()    {}

func (m *KamajiMessage_Command) GetID() string {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return ""
}

type KamajiMessage_NodeItem struct {
	Id               *string `protobuf:"bytes,17,req,name=id" json:"id,omitempty"`
	State            *int32  `protobuf:"varint,18,opt,name=state" json:"state,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *KamajiMessage_NodeItem) Reset()         { *m = KamajiMessage_NodeItem{} }
func (m *KamajiMessage_NodeItem) String() string { return proto.CompactTextString(m) }
func (*KamajiMessage_NodeItem) ProtoMessage()    {}

func (m *KamajiMessage_NodeItem) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *KamajiMessage_NodeItem) GetState() int32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

type KamajiMessage_JobItem struct {
	Name             *string `protobuf:"bytes,19,req,name=name" json:"name,omitempty"`
	Id               *string `protobuf:"bytes,20,req,name=id" json:"id,omitempty"`
	State            *int32  `protobuf:"varint,21,opt,name=state" json:"state,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *KamajiMessage_JobItem) Reset()         { *m = KamajiMessage_JobItem{} }
func (m *KamajiMessage_JobItem) String() string { return proto.CompactTextString(m) }
func (*KamajiMessage_JobItem) ProtoMessage()    {}

func (m *KamajiMessage_JobItem) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *KamajiMessage_JobItem) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *KamajiMessage_JobItem) GetState() int32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

type KamajiMessage_TaskItem struct {
	Name             *string `protobuf:"bytes,22,req,name=name" json:"name,omitempty"`
	Id               *string `protobuf:"bytes,23,req,name=id" json:"id,omitempty"`
	State            *int32  `protobuf:"varint,24,opt,name=state" json:"state,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *KamajiMessage_TaskItem) Reset()         { *m = KamajiMessage_TaskItem{} }
func (m *KamajiMessage_TaskItem) String() string { return proto.CompactTextString(m) }
func (*KamajiMessage_TaskItem) ProtoMessage()    {}

func (m *KamajiMessage_TaskItem) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *KamajiMessage_TaskItem) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *KamajiMessage_TaskItem) GetState() int32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

type KamajiMessage_CommandItem struct {
	Name             *string `protobuf:"bytes,25,req,name=name" json:"name,omitempty"`
	Id               *string `protobuf:"bytes,26,req,name=id" json:"id,omitempty"`
	State            *int32  `protobuf:"varint,27,opt,name=state" json:"state,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *KamajiMessage_CommandItem) Reset()         { *m = KamajiMessage_CommandItem{} }
func (m *KamajiMessage_CommandItem) String() string { return proto.CompactTextString(m) }
func (*KamajiMessage_CommandItem) ProtoMessage()    {}

func (m *KamajiMessage_CommandItem) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *KamajiMessage_CommandItem) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *KamajiMessage_CommandItem) GetState() int32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func init() {
	proto.RegisterType((*KamajiMessage)(nil), "proto_msg.KamajiMessage")
	proto.RegisterType((*KamajiMessage_StatusUpdate)(nil), "proto_msg.KamajiMessage.StatusUpdate")
	proto.RegisterType((*KamajiMessage_NodeStats)(nil), "proto_msg.KamajiMessage.NodeStats")
	proto.RegisterType((*KamajiMessage_CommandLog)(nil), "proto_msg.KamajiMessage.CommandLog")
	proto.RegisterType((*KamajiMessage_Command)(nil), "proto_msg.KamajiMessage.Command")
	proto.RegisterType((*KamajiMessage_NodeItem)(nil), "proto_msg.KamajiMessage.NodeItem")
	proto.RegisterType((*KamajiMessage_JobItem)(nil), "proto_msg.KamajiMessage.JobItem")
	proto.RegisterType((*KamajiMessage_TaskItem)(nil), "proto_msg.KamajiMessage.TaskItem")
	proto.RegisterType((*KamajiMessage_CommandItem)(nil), "proto_msg.KamajiMessage.CommandItem")
	proto.RegisterEnum("proto_msg.KamajiMessage_ACTION", KamajiMessage_ACTION_name, KamajiMessage_ACTION_value)
	proto.RegisterEnum("proto_msg.KamajiMessage_ENTITY", KamajiMessage_ENTITY_name, KamajiMessage_ENTITY_value)
}
